version: "3.9"

services:
  frontend:
    restart: unless-stopped
    environment:
      - WATCHPACK_POLLING=true

  backend:
    restart: unless-stopped
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload", "--log-level", "debug"]
    environment:
      - LOG_LEVEL=DEBUG

  db:
    restart: unless-stopped
    ports:
      - "5432:5432"
