[mypy]
python_version = 3.12
warn_unused_configs = True
follow_imports = normal
ignore_missing_imports = True
check_untyped_defs = True
strict_optional = False
warn_return_any = False
disallow_any_generics = False
disable_error_code = no-untyped-def,no-any-return,no-untyped-call,type-arg,misc,arg-type,union-attr,operator,attr-defined,assignment,call-overload,valid-type,return-value,type-var,import-untyped,import-not-found,call-arg,list-item
