"""catch up models

Revision ID: 709d46bc8b51
Revises: 007_composite_indexes
Create Date: 2026-04-07 08:52:32.333684

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "709d46bc8b51"
down_revision: str | Sequence[str] | None = "007_composite_indexes"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        "idx_password_reset_tokens_user", "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "status_changes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("changed_by", sa.UUID(), nullable=True),
        sa.Column("old_status", sa.String(length=20), nullable=True),
        sa.Column("new_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_status_changes_club", "status_changes", ["club_id"], unique=False)
    op.create_table(
        "beschikbaarheid",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("ronde_id", sa.UUID(), nullable=False),
        sa.Column("is_beschikbaar", sa.Boolean(), nullable=False),
        sa.Column("notitie", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["ronde_id"], ["speelrondes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "ronde_id", name="uq_beschikbaarheid_team_ronde"),
    )
    op.create_index("idx_beschikbaarheid_ronde", "beschikbaarheid", ["ronde_id"], unique=False)
    op.create_index("idx_beschikbaarheid_team", "beschikbaarheid", ["team_id"], unique=False)
    op.alter_column(
        "baantoewijzingen",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "baantoewijzingen",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "banen",
        "verlichting_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'geen'::character varying"),
    )
    op.alter_column(
        "banen",
        "overdekt",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "banen",
        "prioriteit_score",
        existing_type=sa.SMALLINT(),
        nullable=False,
        existing_server_default=sa.text("'5'::smallint"),
    )
    op.alter_column(
        "banen",
        "actief",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "banen",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "banen",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column("clubs", sa.Column("max_thuisteams_per_dag", sa.SmallInteger(), nullable=False))
    op.add_column(
        "clubs", sa.Column("banen_types", postgresql.ARRAY(sa.String(length=20)), nullable=False)
    )
    op.add_column("clubs", sa.Column("billing_info", sa.Text(), nullable=True))
    op.alter_column(
        "clubs",
        "primary_color",
        existing_type=sa.VARCHAR(length=7),
        nullable=False,
        existing_server_default=sa.text("'#1B5E20'::character varying"),
    )
    op.alter_column(
        "clubs",
        "secondary_color",
        existing_type=sa.VARCHAR(length=7),
        nullable=False,
        existing_server_default=sa.text("'#FFFFFF'::character varying"),
    )
    op.alter_column(
        "clubs",
        "accent_color",
        existing_type=sa.VARCHAR(length=7),
        nullable=False,
        existing_server_default=sa.text("'#FFC107'::character varying"),
    )
    op.alter_column(
        "clubs",
        "font_choice",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'default'::character varying"),
    )
    op.alter_column(
        "clubs",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'trial'::character varying"),
    )
    op.alter_column(
        "clubs",
        "max_banen",
        existing_type=sa.SMALLINT(),
        nullable=False,
        existing_server_default=sa.text("'8'::smallint"),
    )
    op.alter_column(
        "clubs",
        "max_competities",
        existing_type=sa.SMALLINT(),
        nullable=False,
        existing_server_default=sa.text("'5'::smallint"),
    )
    op.alter_column(
        "clubs",
        "payment_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "clubs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "clubs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_clubs_slug"), table_name="clubs")
    op.drop_index(op.f("idx_clubs_status"), table_name="clubs")
    op.add_column(
        "competities", sa.Column("email_notifications_enabled", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "competities", sa.Column("reminder_days_before", sa.SmallInteger(), nullable=False)
    )
    op.alter_column(
        "competities",
        "feestdagen",
        existing_type=postgresql.ARRAY(sa.DATE()),
        nullable=False,
        existing_server_default=sa.text("'{}'::date[]"),
    )
    op.alter_column(
        "competities",
        "inhaal_datums",
        existing_type=postgresql.ARRAY(sa.DATE()),
        nullable=False,
        existing_server_default=sa.text("'{}'::date[]"),
    )
    op.alter_column(
        "competities",
        "actief",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "competities",
        "standaard_starttijden",
        existing_type=postgresql.ARRAY(postgresql.TIME()),
        nullable=False,
        existing_server_default=sa.text("'{}'::time without time zone[]"),
    )
    op.alter_column(
        "competities",
        "hergebruik_configuratie",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "competities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competition_prices",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competition_prices",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "invite_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "invite_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "mollie_config",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "mollie_config",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "payments",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "payments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "payments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "planninghistorie",
        "aantal_keer",
        existing_type=sa.SMALLINT(),
        nullable=False,
        existing_server_default=sa.text("'0'::smallint"),
    )
    op.alter_column(
        "planninghistorie",
        "totaal_score",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "planninghistorie",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sepa_mandates",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "sepa_mandates",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sepa_mandates",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "speelrondes",
        "is_inhaalronde",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "speelrondes",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'concept'::character varying"),
    )
    op.alter_column(
        "speelrondes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "speelrondes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column("teams", sa.Column("public_token", sa.String(length=64), nullable=False))
    op.alter_column(
        "teams",
        "actief",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "teams",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "teams",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_unique_constraint(None, "teams", ["public_token"])
    op.add_column("users", sa.Column("email_opt_out", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("onboarding_completed", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("failed_login_attempts", sa.SmallInteger(), nullable=False))
    op.add_column("users", sa.Column("locked_until", sa.DateTime(), nullable=True))
    op.alter_column(
        "users",
        "is_superadmin",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_users_club"), table_name="users")
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.add_column("wedstrijden", sa.Column("competitie_id", sa.UUID(), nullable=False))
    op.add_column("wedstrijden", sa.Column("speeldatum", sa.Date(), nullable=True))
    op.add_column("wedstrijden", sa.Column("speeltijd", sa.Time(), nullable=True))
    op.add_column("wedstrijden", sa.Column("baan_id", sa.UUID(), nullable=True))
    op.add_column("wedstrijden", sa.Column("uitslag_thuisteam", sa.SmallInteger(), nullable=True))
    op.add_column("wedstrijden", sa.Column("uitslag_uitteam", sa.SmallInteger(), nullable=True))
    op.add_column("wedstrijden", sa.Column("scorendetails", sa.Text(), nullable=True))
    op.add_column("wedstrijden", sa.Column("notitie", sa.Text(), nullable=True))
    op.alter_column(
        "wedstrijden",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'ingepland'::character varying"),
    )
    op.alter_column(
        "wedstrijden",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "wedstrijden",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index("idx_wedstrijden_competitie", "wedstrijden", ["competitie_id"], unique=False)
    op.create_foreign_key(
        None, "wedstrijden", "competities", ["competitie_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "wedstrijden", "banen", ["baan_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wedstrijden", type_="foreignkey")
    op.drop_constraint(None, "wedstrijden", type_="foreignkey")
    op.drop_index("idx_wedstrijden_competitie", table_name="wedstrijden")
    op.alter_column(
        "wedstrijden",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "wedstrijden",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "wedstrijden",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'ingepland'::character varying"),
    )
    op.drop_column("wedstrijden", "notitie")
    op.drop_column("wedstrijden", "scorendetails")
    op.drop_column("wedstrijden", "uitslag_uitteam")
    op.drop_column("wedstrijden", "uitslag_thuisteam")
    op.drop_column("wedstrijden", "baan_id")
    op.drop_column("wedstrijden", "speeltijd")
    op.drop_column("wedstrijden", "speeldatum")
    op.drop_column("wedstrijden", "competitie_id")
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("idx_users_club"), "users", ["club_id"], unique=False)
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "users",
        "is_superadmin",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_column("users", "locked_until")
    op.drop_column("users", "failed_login_attempts")
    op.drop_column("users", "onboarding_completed")
    op.drop_column("users", "email_opt_out")
    op.drop_constraint(None, "teams", type_="unique")
    op.alter_column(
        "teams",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "teams",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "teams",
        "actief",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.drop_column("teams", "public_token")
    op.alter_column(
        "speelrondes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "speelrondes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "speelrondes",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'concept'::character varying"),
    )
    op.alter_column(
        "speelrondes",
        "is_inhaalronde",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "sepa_mandates",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sepa_mandates",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sepa_mandates",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "planninghistorie",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "planninghistorie",
        "totaal_score",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "planninghistorie",
        "aantal_keer",
        existing_type=sa.SMALLINT(),
        nullable=True,
        existing_server_default=sa.text("'0'::smallint"),
    )
    op.alter_column(
        "payments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "payments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "payments",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "mollie_config",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "mollie_config",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "invite_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "invite_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "competition_prices",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competition_prices",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "competities",
        "hergebruik_configuratie",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "competities",
        "standaard_starttijden",
        existing_type=postgresql.ARRAY(postgresql.TIME()),
        nullable=True,
        existing_server_default=sa.text("'{}'::time without time zone[]"),
    )
    op.alter_column(
        "competities",
        "actief",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "competities",
        "inhaal_datums",
        existing_type=postgresql.ARRAY(sa.DATE()),
        nullable=True,
        existing_server_default=sa.text("'{}'::date[]"),
    )
    op.alter_column(
        "competities",
        "feestdagen",
        existing_type=postgresql.ARRAY(sa.DATE()),
        nullable=True,
        existing_server_default=sa.text("'{}'::date[]"),
    )
    op.drop_column("competities", "reminder_days_before")
    op.drop_column("competities", "email_notifications_enabled")
    op.create_index(op.f("idx_clubs_status"), "clubs", ["status"], unique=False)
    op.create_index(op.f("idx_clubs_slug"), "clubs", ["slug"], unique=False)
    op.alter_column(
        "clubs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "clubs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "clubs",
        "payment_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "clubs",
        "max_competities",
        existing_type=sa.SMALLINT(),
        nullable=True,
        existing_server_default=sa.text("'5'::smallint"),
    )
    op.alter_column(
        "clubs",
        "max_banen",
        existing_type=sa.SMALLINT(),
        nullable=True,
        existing_server_default=sa.text("'8'::smallint"),
    )
    op.alter_column(
        "clubs",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'trial'::character varying"),
    )
    op.alter_column(
        "clubs",
        "font_choice",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'default'::character varying"),
    )
    op.alter_column(
        "clubs",
        "accent_color",
        existing_type=sa.VARCHAR(length=7),
        nullable=True,
        existing_server_default=sa.text("'#FFC107'::character varying"),
    )
    op.alter_column(
        "clubs",
        "secondary_color",
        existing_type=sa.VARCHAR(length=7),
        nullable=True,
        existing_server_default=sa.text("'#FFFFFF'::character varying"),
    )
    op.alter_column(
        "clubs",
        "primary_color",
        existing_type=sa.VARCHAR(length=7),
        nullable=True,
        existing_server_default=sa.text("'#1B5E20'::character varying"),
    )
    op.drop_column("clubs", "billing_info")
    op.drop_column("clubs", "banen_types")
    op.drop_column("clubs", "max_thuisteams_per_dag")
    op.alter_column(
        "banen",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "banen",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "banen",
        "actief",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "banen",
        "prioriteit_score",
        existing_type=sa.SMALLINT(),
        nullable=True,
        existing_server_default=sa.text("'5'::smallint"),
    )
    op.alter_column(
        "banen",
        "overdekt",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "banen",
        "verlichting_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'geen'::character varying"),
    )
    op.alter_column(
        "baantoewijzingen",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "baantoewijzingen",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("idx_beschikbaarheid_team", table_name="beschikbaarheid")
    op.drop_index("idx_beschikbaarheid_ronde", table_name="beschikbaarheid")
    op.drop_table("beschikbaarheid")
    op.drop_index("idx_status_changes_club", table_name="status_changes")
    op.drop_table("status_changes")
    op.drop_index("idx_password_reset_tokens_user", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    # ### end Alembic commands ###
