"""add missing club fields

Revision ID: 9ac07d06ca65
Revises: 20260412_toewijzing_snap
Create Date: 2026-04-12 06:39:17.513498

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ac07d06ca65'
down_revision: str | Sequence[str] | None = '20260412_toewijzing_snap'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_toewijzingen_ronde_baan', 'baantoewijzingen', ['ronde_id', 'baan_id'], unique=False)
    op.create_index('idx_banen_club_actief_nummer', 'banen', ['club_id', 'actief', 'nummer'], unique=False)
    op.add_column('clubs', sa.Column('heeft_buitenbanen', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('clubs', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('clubs', sa.Column('longitude', sa.Float(), nullable=True))
    op.alter_column('mollie_config', 'api_key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.create_index('idx_rondes_club_status', 'speelrondes', ['club_id', 'status'], unique=False)
    op.create_index('idx_teams_club_competitie', 'teams', ['club_id', 'competitie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_teams_club_competitie', table_name='teams')
    op.drop_index('idx_rondes_club_status', table_name='speelrondes')
    op.alter_column('mollie_config', 'api_key',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('clubs', 'longitude')
    op.drop_column('clubs', 'latitude')
    op.drop_column('clubs', 'heeft_buitenbanen')
    op.drop_index('idx_banen_club_actief_nummer', table_name='banen')
    op.drop_index('idx_toewijzingen_ronde_baan', table_name='baantoewijzingen')
    # ### end Alembic commands ###
